# Generated by Django 5.1.3 on 2025-05-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('pickup', models.DateField()),
                ('dropoff', models.DateField()),
            ],
        ),
    ]
